version: 2.1 
parameters: 
  sample: 
    type: boolean 
    default: false 
orbs: 
   
  python: circleci/python@1.2 
 
workflows: 
  sample:   
    jobs: 
      - build-and-test 
 
jobs: 
  build-and-test:   
    parallelism: 4 
    docker: 
      - image: cobadoc/manaon 
     
    steps: 
      - checkout 
      - run: 
          name: Run tests 
          no_output_timeout: 5h 
          command: | 
           echo mantab
